# Generated by Django 5.2.11 on 2026-05-04 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='garmin_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='garmin_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='garmin_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='strava_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='strava_athlete_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='strava_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='strava_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActiviteExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('STRAVA', 'Strava'), ('GARMIN', 'Garmin')], max_length=20)),
                ('external_id', models.CharField(help_text="ID unique de l'activité sur Strava/Garmin", max_length=255, unique=True)),
                ('nom', models.CharField(help_text="Titre de l'activité (ex: Course matinale)", max_length=255)),
                ('type_activite', models.CharField(help_text='Run, Ride, Swim, Workout...', max_length=100)),
                ('date_debut', models.DateTimeField()),
                ('distance_metres', models.FloatField(blank=True, null=True)),
                ('temps_secondes', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('frequence_cardiaque_moyenne', models.FloatField(blank=True, null=True)),
                ('donnees_brutes', models.JSONField(blank=True, default=dict, help_text="Stocke toute la réponse brute de l'API au cas où")),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_externes', to='core.client')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
