# Generated by Django 5.2.11 on 2026-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='salles',
            field=models.ManyToManyField(blank=True, related_name='coachs_affilies', to='core.salle'),
        ),
    ]
