# Generated by Django 5.2.11 on 2026-05-13 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coach_salles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='core.salle'),
        ),
        migrations.CreateModel(
            name='ResponsableSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='core.salle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
