# Generated by Django 5.2.11 on 2026-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seance_salle_responsablesalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='platform_plan',
            field=models.CharField(choices=[('free', 'Gratuit (Freemium)'), ('premium', 'Premium (Abonnement)')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='coach',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
