# Generated by Django 5.2.11 on 2026-05-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categorieproduit_commande_produit_lignecommande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Petit-déjeuner', 'Petit-déjeuner'), ('Déjeuner', 'Déjeuner'), ('Dîner', 'Dîner'), ('Collation', 'Collation'), ('Pre-workout', 'Pre-workout')], default='Petit-déjeuner', max_length=50)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('proteines', models.PositiveIntegerField(default=0)),
                ('glucides', models.PositiveIntegerField(default=0)),
                ('lipides', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='core.coach')),
            ],
        ),
        migrations.CreateModel(
            name='PlanNutritionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_nutritionnels', to='core.coach')),
                ('produit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_source', to='core.produit')),
                ('recettes', models.ManyToManyField(related_name='plans', to='core.recette')),
            ],
        ),
    ]
