# Generated by Django 5.2.11 on 2026-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recette_plannutritionnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannutritionnel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plans_nutrition/'),
        ),
    ]
