# Generated by Django 5.2.11 on 2026-05-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coach_platform_plan_coach_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='ID du compte Stripe Connect du coach', max_length=255, null=True),
        ),
    ]
