# Generated by Django 5.2.11 on 2026-05-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coach_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
