# Generated by Django 5.2.11 on 2026-05-27 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_devis_status_accepte_refuse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieproduit',
            options={'verbose_name': 'Catégorie de Produit', 'verbose_name_plural': 'Catégories de Produits'},
        ),
        migrations.AlterField(
            model_name='commande',
            name='order_number',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='NotificationResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('SEANCE', 'Séance'), ('COACH', 'Coach'), ('SALLE', 'Salle'), ('URGENT', 'Urgent'), ('INFO', 'Information')], default='INFO', max_length=20)),
                ('est_lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_responsable', to='core.responsablesalle')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
