# Generated by Django 5.2.11 on 2026-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_categorieproduit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='coachs_bannis',
            field=models.ManyToManyField(blank=True, related_name='salles_bannies', to='core.coach'),
        ),
    ]
